# Generated by Django 5.1.15 on 2026-06-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('hr', 'HR'), ('legal', 'Legal'), ('logistics', 'Logistics'), ('finance', 'Finance'), ('general', 'General')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('definition', models.JSONField(default=dict)),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('trigger_type', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'Schedule'), ('webhook', 'Webhook'), ('event', 'Internal Event'), ('form', 'Form Submission')], default='manual', max_length=16)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('variables_schema', models.JSONField(blank=True, default=dict)),
                ('sla_hours', models.PositiveIntegerField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workflows', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflows', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflows', to='organizations.organization')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='workflows.workflowtemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('node_type', models.CharField(choices=[('trigger', 'Trigger'), ('action', 'Action'), ('condition', 'Condition'), ('approval', 'Approval'), ('delay', 'Delay'), ('parallel', 'Parallel Split'), ('join', 'Join'), ('transform', 'Data Transform'), ('notification', 'Notification'), ('integration', 'Integration Call'), ('human_task', 'Human Task'), ('subflow', 'Sub-workflow')], max_length=32)),
                ('label', models.CharField(max_length=255)),
                ('config', models.JSONField(default=dict)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('retry_policy', models.JSONField(blank=True, default=dict)),
                ('timeout_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
            options={
                'ordering': ['key'],
                'unique_together': {('workflow', 'key')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.JSONField(blank=True, default=dict)),
                ('label', models.CharField(blank=True, max_length=128)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges', to='workflows.workflow')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing', to='workflows.workflownode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming', to='workflows.workflownode')),
            ],
            options={
                'unique_together': {('workflow', 'source', 'target')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('snapshot', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('changelog', models.TextField(blank=True)),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('workflow', 'version_number')},
            },
        ),
    ]
