"""Generate GitHub Action workflow for Specwright CI."""

SPECWRIGHT_WORKFLOW = """# Generated by Specwright — paste into .github/workflows/specwright.yml
name: Specwright

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  spec-health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Specwright CLI deps
        run: pip install httpx pyyaml

      - name: Validate API documentation freshness
        env:
          SPECWRIGHT_API: ${{ vars.SPECWRIGHT_API_URL || 'http://localhost:8080' }}
        run: |
          python - <<'PY'
          import os, sys, json
          from pathlib import Path
          import urllib.request

          root = Path(".").resolve()
          api = os.environ.get("SPECWRIGHT_API", "http://127.0.0.1:8080").rstrip("/")

          # Fail if committed OpenAPI is older than route sources (simple drift guard)
          spec = root / "docs" / "openapi.yaml"
          py_files = list(root.rglob("*.py"))
          if not py_files:
              print("No Python files — skip")
              sys.exit(0)

          latest_py = max(p.stat().st_mtime for p in py_files if p.is_file())
          if spec.exists() and spec.stat().st_mtime < latest_py - 60:
              print("::error::OpenAPI spec is stale — run Specwright watch mode or regenerate docs")
              sys.exit(1)

          print("Specwright CI check passed — docs/openapi.yaml is fresh")
          PY
"""


def generate_github_action() -> str:
    return SPECWRIGHT_WORKFLOW
