# Generated by Django 5.1.15 on 2026-06-04 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('recurring_issue', 'Recurring Issue'), ('stale_access', 'Stale Access'), ('sla_risk', 'SLA At Risk'), ('entity_history', 'Entity History')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('detail', models.TextField()),
                ('subject_key', models.CharField(blank=True, db_index=True, max_length=128)),
                ('occurrence_count', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=16)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='organizations.organization')),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='ProactiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('sla_breach', 'SLA Breach Imminent'), ('approval_overdue', 'Approval Overdue'), ('case_stuck', 'Case Stuck in Stage'), ('integration_failure', 'Integration Failure Spike'), ('access_review_due', 'Access Review Due')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('severity', models.CharField(default='warning', max_length=16)),
                ('subject_key', models.CharField(blank=True, max_length=128)),
                ('acknowledged', models.BooleanField(default=False)),
                ('escalated', models.BooleanField(default=False)),
                ('slack_message_ts', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='organizations.organization')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proactive_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
