# Generated by Django 5.1.15 on 2026-06-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DomainEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('organization_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('aggregate_type', models.CharField(blank=True, max_length=64)),
                ('aggregate_id', models.CharField(blank=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('correlation_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization_id', 'event_type', '-created_at'], name='events_doma_organiz_066c99_idx')],
            },
        ),
    ]
