# Generated by Django 5.1.15 on 2026-06-04 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('triage', 'Case Triage'), ('copilot', 'Copilot Turn'), ('risk_scan', 'Risk Scan'), ('draft', 'Draft Communication')], max_length=32)),
                ('vertical', models.CharField(max_length=32)),
                ('prompt_snapshot', models.JSONField(default=dict)),
                ('result', models.JSONField(default=dict)),
                ('confidence', models.FloatField(default=0)),
                ('model_name', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to='cases.case')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_assessments', to='organizations.organization')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AICopilotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=16)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.aiassessment')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copilot_messages', to='cases.case')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
