# Generated by Django 5.1.15 on 2026-06-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='persona',
            field=models.CharField(blank=True, choices=[('hr_specialist', 'HR Specialist'), ('legal_counsel', 'Legal Counsel'), ('logistics_coordinator', 'Logistics Coordinator'), ('compliance_officer', 'Compliance Officer'), ('ops_admin', 'Operations Admin')], default='ops_admin', max_length=32),
        ),
    ]
