# Generated by Django 5.1.15 on 2026-06-04 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('kind', models.CharField(choices=[('rest', 'REST API'), ('webhook_out', 'Outbound Webhook'), ('email', 'Email'), ('slack', 'Slack'), ('teams', 'Microsoft Teams'), ('google_sheets', 'Google Sheets'), ('sharepoint', 'SharePoint'), ('sap', 'SAP'), ('workday', 'Workday'), ('docusign', 'DocuSign'), ('custom', 'Custom Script')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('config_schema', models.JSONField(default=dict)),
                ('is_system', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connectors', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('encrypted_secrets', models.BinaryField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.connector')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('request_summary', models.JSONField(default=dict)),
                ('response_summary', models.JSONField(default=dict)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=False)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrations.connector')),
            ],
        ),
    ]
