"""Generate pytest scaffolding from discovered routes and Django models."""
from __future__ import annotations

from pathlib import Path


def generate_tests(
    *,
    framework: str,
    routes: list[dict],
    models: list[dict],
    project_name: str,
) -> str:
    lines = [
        '"""',
        f"Test scaffold for {project_name}",
        "Auto-generated by Specwright — customize fixtures before CI.",
        '"""',
        "",
    ]
    if framework == "fastapi":
        lines.extend(_fastapi_tests(routes))
    elif framework == "django":
        lines.extend(_django_tests(routes, models))
    else:
        lines.extend(_generic_tests())

    return "\n".join(lines) + "\n"


def _fastapi_tests(routes: list[dict]) -> list[str]:
    if not routes:
        return [
            "import pytest",
            "",
            "@pytest.fixture",
            "def client():",
            "    from fastapi.testclient import TestClient",
            "    from api.main import app",
            "    return TestClient(app)",
            "",
            "def test_health(client):",
            "    response = client.get('/')",
            "    assert response.status_code in (200, 404)",
            "",
        ]
    lines = [
        "import pytest",
        "",
        "@pytest.fixture",
        "def client():",
        "    from fastapi.testclient import TestClient",
        "    from api.main import app",
        "    return TestClient(app)",
        "",
    ]
    seen = set()
    for r in routes:
        key = (r["method"], r["path"])
        if key in seen:
            continue
        seen.add(key)
        fname = f"test_{r['name']}_{r['method'].lower()}".replace("-", "_").replace("/", "_")[:60]
        path = r["path"]
        method = r["method"].lower()
        lines.append(f"def {fname}(client):")
        if method == "get":
            lines.append(f"    response = client.get('{path}')")
        elif method == "post":
            lines.append(f"    response = client.post('{path}', json={{}})")
        else:
            lines.append(f"    response = client.request('{r['method']}', '{path}')")
        lines.append("    assert response.status_code < 500")
        lines.append("")
    return lines


def _django_tests(routes: list[dict], models: list[dict]) -> list[str]:
    lines = [
        "import pytest",
        "from django.test import Client",
        "",
        "@pytest.fixture",
        "def client():",
        "    return Client()",
        "",
    ]
    lines.extend(_django_api_tests(routes))
    lines.extend(_django_model_tests(models))
    return lines


def _django_api_tests(routes: list[dict]) -> list[str]:
    if not routes:
        return [
            "def test_root(client):",
            "    response = client.get('/')",
            "    assert response.status_code in (200, 301, 302, 404)",
            "",
        ]
    lines: list[str] = []
    seen: set[tuple[str, str]] = set()
    for r in routes:
        key = (r["method"], r["path"])
        if key in seen:
            continue
        seen.add(key)
        fname = f"test_{r['name']}_{r['method'].lower()}".replace("-", "_").replace("/", "_")[:60]
        path = r["path"]
        method = r["method"].lower()
        lines.append(f"def {fname}(client):")
        if method == "get":
            lines.append(f"    response = client.get('{path}')")
        elif method == "post":
            lines.append(
                f"    response = client.post('{path}', data={{}}, content_type='application/json')"
            )
        else:
            lines.append(f"    response = client.generic('{r['method']}', '{path}')")
        lines.append("    assert response.status_code < 500")
        lines.append("")
    return lines


def _django_model_tests(models: list[dict]) -> list[str]:
    lines = [
        "@pytest.mark.django_db",
        "class TestModelsSmoke:",
        "    '''Smoke tests — extend with factory_boy fixtures.'''",
        "",
    ]
    if not models:
        lines.append("    def test_placeholder(self):")
        lines.append("        assert True")
        lines.append("")
        return lines
    for m in models[:20]:
        lines.append(f"    def test_{m['name'].lower()}_can_import(self):")
        mod = m["module"].replace("/", ".").replace(".py", "")
        lines.append(f"        from {mod} import {m['name']}")
        lines.append(f"        assert {m['name']} is not None")
        lines.append("")
    return lines


def _generic_tests() -> list[str]:
    return [
        "def test_project_imports():",
        "    assert True",
        "",
    ]


def models_from_django_analysis(files: list[Path], root: Path) -> list[dict]:
    from .django_models import analyze_django_models

    _, _ = analyze_django_models(files, root)
    import ast
    import re

    models = []
    for fp in files:
        if "models.py" not in fp.name:
            continue
        try:
            tree = ast.parse(fp.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        module = str(fp.relative_to(root)).replace("\\", "/")
        for node in ast.walk(tree):
            if isinstance(node, ast.ClassDef) and "Model" in ast.unparse(node):
                models.append({"name": node.name, "module": module})
    return models
